#! /usr/bin/env bash

set -e

# This script automates the split, compression, encryption and the 
# upload, both to a mounted directorie and to a telegram channel.

# You should also configure the python script with your credentials

# Usage: 	
# Add to crontab 
# * * * * * /path/to/tg-backup

### ----- Change this values -----

tgbot_dir='/path/to/tgbot-upload.py/dir'
dir='/path/to/backup/dir'
bup_dir='/path/to/save/backup/dir'
filename='name_of_encrypted_files'
pass='super strong password for encrypted drives'

### ----- script -----

# Create compressed backup splited in 1.5G size and create checksum
7z a -t7z -v1536m -m0=lzma2 -mx=9 -mfb=64 -md=32m -ms=on -mhe=on -p"${pass}" ${bup_dir}/${filename}-$(date -I).7z ${dir}
bash -c "find $bup_dir -type f -mmin -60 -exec sha256sum {} \;" > ${bup_dir}/${filename}-$(date -I).7z.sha256

# Send files to telegram channel
cd $tgbot_dir
find $bup_dir -type f -mmin -60 -exec $tgbot_dir/tgbot-upload.py -f {} \;

# Delete older backups, only local, not from telegram
find $bup_dir -type f -mtime +7 -name '*.7z*' -delete

