#! /usr/bin/env bash

set -e

# This script makes automatic the compression, encryption and the upload, both to a mounted directorie and to a telegram channel
# Usage: 	backup-cloud <file-or-directorie-to-backup>

### ----- Change this values -----

_mount_path=/path/to/backup/directorie
_telegram_channel_name=backup
_password=1234

### ----- variables -----

_fn=$1
filename=$(echo ${_fn} | sed 's:/*$::')
_msg=$(echo "Backing up ${filename}")
_md=$_mount_path
_tg=$_telegram_channel_name
_ps=$_password

### ----- script -----

if [ -z "$filename" ]; then
	echo "You are mising the file name."
    	exit 1
fi
if  ! [ -f $filename ] && ! [ -d $filename ]; then
    	echo 
	echo "The file $filename doesn't exist."
    	exit 1
fi

7z a -t7z -m0=lzma2 -mx=9 -mfb=64 -md=32m -ms=on -mhe=on -p"${_ps}" ${_md}/${filename}-$(date +"%Y-%m-%d").7z $filename
telegram-cli -W --exec "msg ${_tg} ""${_msg}"
telegram-cli -W --exec "send_file ${_tg} ""${_md}/${filename}-$(date +"%Y-%m-%d").7z"
